### ISSUE TITLE
Seed values greater than ~230k cause thread panicked at 'attempt to multiply with overflow'

### ISSUE THREAD

**Issue by rademonster** [elementh/random_color#10]
extern crate random_color;
use random_color::{Color, Luminosity, RandomColor};
fn main() {
	let color = RandomColor::new()
					  .hue(Color::Blue) // Optional
					  .luminosity(Luminosity::Light) // Optional
					  .seed(260_000) // Optional
					  .to_rgb_array(); //
}

Causes a panic in random_within. I'm very new to rust so I'm not exactly sure the best way to handle this. usize might be large enough type for the random_within calculations that any i32 passed into the function will not cause an overflow.

Thanks for the library

**Comment by elementh** [comment]
Hey @rademonster , thanks for opening an issue.

I'll have a look at the logic this weekend and try to fix it asap.
