### ISSUE TITLE
I think the `seed` function broken

### ISSUE THREAD

**Issue by EFanZh** [elementh/random_color#17]
https://github.com/elementh/random_color/blob/433c62b4a13d2d64c7ba0f9a9731c69e392e55af/src/lib.rs#L223-L228

Like in the comment, the calculation should be done with float type, but instead, the code always do calculation with integer type. So the value of `rnd` in line 226 is always 0, so the generated random number is always `min`.

Also, the multiplication in line 225 could cause the result to overflow which will panic the program.

**Comment by elementh** [comment]
That may be indeed possible, I'll look at it, thanks!
