### ISSUE TITLE
to_rgb_array should return [u8;3] instead of [u32;3]

### ISSUE THREAD

**Issue by RReverser** [elementh/random_color#20]
RGB values are always in range of 0-255, so it would make more sense to return `[u8; 3]`. This would make it also easier to pass the returned color to other APIs / crates that expect `u8` values.

**Comment by elementh** [comment]
Fair enough, will try to make the changes over next week, but if you are open to contribute I'll gladly review any PR :)

**Comment by RReverser** [comment]
Might give it a try later, but no promises - quite buried myself at the moment, just something I noticed while quickly switching from custom ad-hoc solution to your crate :)

**Comment by elementh** [comment]
No worries, I'm on the same situation. Glad to hear you are planning on switching to random_color! I'm struggling to find any new feature I may be missing or could be useful, so if you have any necessities or ideas while switching, just let me know!!

**Comment by elementh** [comment]
So, I found 5 spare minutes and made the changes, I'm very sleepy right now but should be all good and working, let me know if something is wrong!

**Comment by RReverser** [comment]
Ha, that was quick, thanks! I see you bumped the version but it doesn't seem to be yet on crates.io?

**Comment by RReverser** [comment]
Oh, now there's 0.6.1.

**Comment by elementh** [comment]
Yeah, I will totally correct it tomorrow, but I think I copied it wrong!

**Comment by RReverser** [comment]
Works great, thanks for the quick fix!

![image](https://user-images.githubusercontent.com/557590/135344794-b89ed03a-3d10-436b-98b8-9b3b22154d4e.png)
