### ISSUE TITLE
random alpha documentation

### ISSUE THREAD

**Issue by TheIronBorn** [elementh/random_color#6]
I was looking through the code and spotted that random alpha values are generated if `alpha` is `None`.  Currently the only way to do that to use struct initialization like so:
```rust
let color = Color {
    alpha: None,
    ..Color::new()
};
```

I think this functionality should be noted in the documentation somewhere.

**Comment by elementh** [comment]
You are totally right.

I was thinking about introducing `Color::new().random_alpha()` or something like that.
