### ISSUE TITLE
Let the caller choose the random number generator.

### ISSUE THREAD

**Issue by elementh** [elementh/random_color#8]
Functions and methods that use random numbers should probably have a signature like `fn pick_brightness<R: Rng>(&self, rng: &mut R, ...)` and then it should call `rng.gen_range`.

It should provide convenience methods that use some default so specifying a Rng doesn't becomes mandatory.

**Comment by nms-scribe** [comment]
I was looking for this capability, the issue says it's completed, but I don't see this in the API. Would it be possible to revisit this and add this as a feature?

**Comment by daxpedda** [comment]
`SmallRng` is not portable, which won't make it work in e.g. multiplayer scenarios. 
But more importantly, it can't be "saved & loaded", because `SmallRng` doesn't support retrieving the seed or Serde.
